export type LanguageCode =
    | "en" // English
    | "es" // Spanish
    | "zh" // Chinese (Mandarin)
    | "ru" // Russian
    | "bn" // Bengali
    | "ht" // Haitian Creole
    | "ko" // Korean
    | "ar" // Arabic
    | "fr" // French
    | "ur"; // Urdu

export interface Language {
    code: LanguageCode;
    name: string;
    nativeName: string;
    speechCode: string; // BCP 47 language tag for SpeechRecognition
}

export const LANGUAGES: Language[] = [
    { code: "en", name: "English", nativeName: "English", speechCode: "en-US" },
    { code: "es", name: "Spanish", nativeName: "Español", speechCode: "es-US" },
    { code: "zh", name: "Chinese", nativeName: "中文", speechCode: "zh-CN" },
    { code: "ru", name: "Russian", nativeName: "Русский", speechCode: "ru-RU" },
    { code: "bn", name: "Bengali", nativeName: "বাংলা", speechCode: "bn-BD" },
    { code: "ht", name: "Haitian Creole", nativeName: "Kreyòl Ayisyen", speechCode: "ht-HT" },
    { code: "ko", name: "Korean", nativeName: "한국어", speechCode: "ko-KR" },
    { code: "ar", name: "Arabic", nativeName: "العربية", speechCode: "ar-SA" },
    { code: "fr", name: "French", nativeName: "Français", speechCode: "fr-FR" },
    { code: "ur", name: "Urdu", nativeName: "اردو", speechCode: "ur-PK" },
];

export const DICTIONARY: Record<LanguageCode, Record<string, string>> = {
    en: {
        "app.title": "CareNet",
        "search.placeholder": "Search hospitals, specialties...",
        "mode.all": "All",
        "mode.emergency": "Emergency",
        "mode.urgent_care": "Urgent Care",
        "nav.profile": "My Profile",
        "nav.signout": "Sign Out",
        "triage.title": "Describe your situation",
        "triage.subtitle": "Tell us what happened and what kind of care you need.",
        "triage.voice_btn": "Voice AI Triage",
        "triage.manual_btn": "Manual Entry",
        "triage.listening": "Listening...",
        "triage.analyzing": "Analyzing...",
        "triage.stop": "Stop & analyze",
        "triage.try_again": "Try again",
        "triage.apply": "Apply to my situation",
        "footer.disclaimer": "Not medical advice · For emergencies call 911",

        // Voice Mode
        "triage.start_speaking": "Start speaking",
        "triage.voice_instruction": "Describe your symptoms by voice",
        "triage.voice_subtext": "Tap the button and describe what happened, your symptoms, and how you are feeling. Our AI will categorize your injury and recommend the right care.",

        // Insurance Form
        "insurance.title": "Your insurance details",
        "insurance.subtitle": "This helps us estimate coverage and out-of-pocket costs at each hospital.",
        "insurance.privacy": "Your data stays on your device and is never sent to any server.",
        "insurance.quick_scan": "Quick scan",
        "insurance.fastest": "Fastest",
        "insurance.or_manual": "Or enter manually",
        "insurance.provider": "Insurance provider",
        "insurance.provider_placeholder": "Select your provider",
        "insurance.plan_type": "Plan type",
        "insurance.plan_type_placeholder": "Select plan type",
        "insurance.network": "Network name",
        "insurance.optional": "(optional)",
        "insurance.network_hint": "Found on the front of your insurance card",
        "insurance.zip": "ZIP code",
        "insurance.zip_hint": "Helps narrow down network coverage",
        "insurance.prefer_network": "Prefer in-network only",
        "insurance.prefer_network_hint": "Only show hospitals verified to accept your plan",
        "insurance.back": "Back",
        "insurance.continue": "Continue",

        // Insurance Scan
        "insurance.scan_title": "Scan insurance card",
        "insurance.scan_subtitle": "Take a photo or upload to auto-fill",
        "insurance.photo_btn": "Photo",
        "insurance.upload_btn": "Upload",

        // Incident Form
        "incident.title": "Describe your situation",
        "incident.subtitle": "Tell us what happened and what kind of care you need.",
        "incident.emergency_alert": "This may be a life-threatening emergency",
        "incident.emergency_action": "If this feels urgent, please call 911 immediately.",
        "incident.description": "What happened?",
        "incident.description_placeholder": "Briefly describe your situation or injury...",
        "incident.care_type": "Type of care needed",
        "incident.symptoms": "Symptoms",
        "incident.symptoms_hint": "Select all that apply so we can assess which hospital capabilities you need.",
        "incident.severity": "How severe is the situation?",

        // Results Screen
        "results.insurance": "Insurance:",
        "results.care": "Care:",
        "results.location_placeholder": "Enter your location (e.g. Midtown)",
        "results.use_gps": "Use GPS",
        "results.locating": "Locating...",
        "results.sort.closest": "Closest first",
        "results.sort.best_match": "Best insurance match",
        "results.sort.lowest_cost": "Lowest cost",
        "results.show_map": "Show map",
        "results.list_only": "List only",
        "results.filters": "Filters",
        "results.filter.capability": "Capabilities",
        "results.filter.insurance": "Insurance status",
        "results.filter.distance": "Max distance",
        "results.filter.clear": "Clear all filters",
        "results.finding": "Finding hospitals...",
        "results.no_results": "No hospitals found",
        "results.no_results_hint": "Try increasing the distance or clearing some filters.",

        // Hospital Card
        "hospital.view_details": "View details",
        "hospital.call": "Call Hospital",
        "hospital.est_cost": "EST. COST",
        "hospital.distance": "DISTANCE",
        "hospital.insurance": "INSURANCE",
        "hospital.verified": "Verified",
        "hospital.out_of_network": "Out of Network",
        "hospital.unknown_coverage": "Unknown Coverage",

        // Data Labels (Care Types, Symptoms, Severity)
        "care_type.emergency": "Emergency Room",
        "care_type.urgent": "Urgent Care",
        "care_type.not-sure": "Not Sure",
        "care_desc.emergency": "Life-threatening or severe condition requiring immediate attention",
        "care_desc.urgent": "Non-life-threatening but needs prompt medical care today",
        "care_desc.not-sure": "We'll help match you based on your symptoms and severity",

        "symptom.chest-pain": "Chest Pain",
        "symptom.stroke": "Stroke Keywords",
        "symptom.major-bleeding": "Major Bleeding",
        "symptom.broken-bone": "Broken Bone",
        "symptom.severe-burn": "Severe Burn",
        "symptom.allergic-reaction": "Allergic Reaction",
        "symptom.high-fever": "High Fever",
        "symptom.head-injury": "Head Injury",
        "symptom.other": "Other / Unsure",

        "severity.mild": "Mild",
        "severity.moderate": "Moderate",
        "severity.severe": "Severe",
        "severity_desc.mild": "Manageable, not worsening",
        "severity_desc.moderate": "Significant but stable",
        "severity_desc.severe": "Intense, worsening fast",
    },
    es: {
        "app.title": "CareNet",
        "search.placeholder": "Buscar hospitales...",
        "mode.all": "Todos",
        "mode.emergency": "Emergencia",
        "mode.urgent_care": "Atención Urgente",
        "nav.profile": "Mi Perfil",
        "nav.signout": "Cerrar Sesión",
        "triage.title": "Describa su situación",
        "triage.subtitle": "Cuéntenos qué pasó y qué atención necesita.",
        "triage.voice_btn": "Filtraje por Voz IA",
        "triage.manual_btn": "Entrada Manual",
        "triage.listening": "Escuchando...",
        "triage.analyzing": "Analizando...",
        "triage.stop": "Detener y analizar",
        "triage.try_again": "Intentar de nuevo",
        "triage.apply": "Aplicar a mi situación",
        "footer.disclaimer": "No es consejo médico · Para emergencias llame al 911",

        "triage.start_speaking": "Comenzar a hablar",
        "triage.voice_instruction": "Describa sus síntomas por voz",
        "triage.voice_subtext": "Toque el botón y describa qué pasó, sus síntomas y cómo se siente. Nuestra IA categorizará su lesión y recomendará la atención adecuada.",

        "insurance.title": "Detalles de seguro",
        "insurance.subtitle": "Ayuda a estimar cobertura y costos.",
        "insurance.privacy": "Sus datos quedan en su dispositivo.",
        "insurance.quick_scan": "Escaneo rápido",
        "insurance.fastest": "Más rápido",
        "insurance.or_manual": "O ingrese manualmente",
        "insurance.provider": "Proveedor de seguro",
        "insurance.provider_placeholder": "Seleccione proveedor",
        "insurance.plan_type": "Tipo de plan",
        "insurance.plan_type_placeholder": "Seleccione plan",
        "insurance.network": "Nombre de red",
        "insurance.optional": "(opcional)",
        "insurance.network_hint": "En el frente de su tarjeta",
        "insurance.zip": "Código postal",
        "insurance.zip_hint": "Ayuda a ubicar la cobertura",
        "insurance.prefer_network": "Preferir dentro de la red",
        "insurance.prefer_network_hint": "Solo hospitales que acepten su plan",
        "insurance.back": "Atrás",
        "insurance.continue": "Continuar",

        "insurance.scan_title": "Escanear tarjeta de seguro",
        "insurance.scan_subtitle": "Tome una foto o suba para autocompletar",
        "insurance.photo_btn": "Foto",
        "insurance.upload_btn": "Subir",

        "incident.title": "Describa su situación",
        "incident.subtitle": "Cuéntenos qué pasó.",
        "incident.emergency_alert": "Puede ser una emergencia vital",
        "incident.emergency_action": "Si es urgente, llame al 911 inmediatamente.",
        "incident.description": "¿Qué pasó?",
        "incident.description_placeholder": "Describa brevemente...",
        "incident.care_type": "Tipo de atención",
        "incident.symptoms": "Síntomas",
        "incident.symptoms_hint": "Seleccione los que apliquen.",
        "incident.severity": "¿Qué tan grave es?",

        "results.insurance": "Seguro:",
        "results.care": "Atención:",
        "results.location_placeholder": "Ingrese ubicación",
        "results.use_gps": "Usar GPS",
        "results.locating": "Ubicando...",
        "results.sort.closest": "Más cercanos",
        "results.sort.best_match": "Mejor coincidencia",
        "results.sort.lowest_cost": "Menor costo",
        "results.show_map": "Ver mapa",
        "results.list_only": "Solo lista",
        "results.filters": "Filtros",
        "results.filter.capability": "Capacidad",
        "results.filter.insurance": "Estado del seguro",
        "results.filter.distance": "Distancia máx",
        "results.filter.clear": "Borrar filtros",
        "results.finding": "Buscando hospitales...",
        "results.no_results": "No se encontraron hospitales",
        "results.no_results_hint": "Intente aumentar la distancia.",

        "hospital.view_details": "Ver detalles",
        "hospital.call": "Llamar Hospital",
        "hospital.est_cost": "COSTO EST.",
        "hospital.distance": "DISTANCIA",
        "hospital.insurance": "SEGURO",
        "hospital.verified": "Verificado",
        "hospital.out_of_network": "Fuera de Red",
        "hospital.unknown_coverage": "Cobertura Desconocida",

        "care_type.emergency": "Urgencias (ER)",
        "care_type.urgent": "Atención Urgente",
        "care_type.not-sure": "No estoy seguro",
        "care_desc.emergency": "Condición grave o amenazante para la vida",
        "care_desc.urgent": "No vital pero requiere atención hoy",
        "care_desc.not-sure": "Le ayudaremos a elegir según sus síntomas",

        "symptom.chest-pain": "Dolor de pecho / dificultad respiratoria",
        "symptom.stroke": "Síntomas de derrame (cara caída, debilidad brazo, habla)",
        "symptom.major-bleeding": "Sangrado mayor",
        "symptom.broken-bone": "Hueso roto / lesión grave",
        "symptom.severe-burn": "Quemadura grave",
        "symptom.allergic-reaction": "Reacción alérgica grave",
        "symptom.high-fever": "Fiebre alta / infección",
        "symptom.head-injury": "Lesión en la cabeza / conmoción",
        "symptom.other": "Otro",

        "severity.mild": "Leve",
        "severity.moderate": "Moderado",
        "severity.severe": "Grave",
        "severity_desc.mild": "Manejable, no empeora",
        "severity_desc.moderate": "Significativo pero estable",
        "severity_desc.severe": "Intenso, empeorando rápido",
    },
    zh: {
        "app.title": "CareNet",
        "search.placeholder": "搜索医院、专科...",
        "mode.all": "全部",
        "mode.emergency": "急诊",
        "mode.urgent_care": "紧急护理",
        "nav.profile": "我的资料",
        "nav.signout": "退出",
        "triage.title": "描述您的况",
        "triage.subtitle": "告诉我们发生了什么以及您需要什么样的护理。",
        "triage.voice_btn": "AI 语音分诊",
        "triage.manual_btn": "手动输入",
        "triage.listening": "正在聆听...",
        "triage.analyzing": "正在分析...",
        "triage.stop": "停止并分析",
        "triage.try_again": "重试",
        "triage.apply": "应用",
        "footer.disclaimer": "非医疗建议 · 紧急情况请拨打 911",

        "triage.start_speaking": "开始说话",
        "triage.voice_instruction": "请用语音描述您的症状",
        "triage.voice_subtext": "点击按钮描述发生的事情、您的症状以及您的感受。我们的 AI 将对您的伤情进行分类并推荐合适的护理。",

        "insurance.title": "保险详情",
        "insurance.subtitle": "帮助估算每家医院的覆盖范围和自付费用。",
        "insurance.privacy": "您的数据仅保存在您的设备上，绝不会发送到任何服务器。",
        "insurance.quick_scan": "快速扫描",
        "insurance.fastest": "最快",
        "insurance.or_manual": "或手动输入",
        "insurance.provider": "保险提供商",
        "insurance.provider_placeholder": "选择提供商",
        "insurance.plan_type": "计划类型",
        "insurance.plan_type_placeholder": "选择计划",
        "insurance.network": "网络名称",
        "insurance.optional": "(可选)",
        "insurance.network_hint": "在保险卡正面",
        "insurance.zip": "邮政编码",
        "insurance.zip_hint": "帮助确定网络覆盖范围",
        "insurance.prefer_network": "仅限网络内",
        "insurance.prefer_network_hint": "仅显示已验证接受您计划的医院",
        "insurance.back": "返回",
        "insurance.continue": "继续",

        "insurance.scan_title": "扫描保险卡",
        "insurance.scan_subtitle": "拍照或上传以自动填写",
        "insurance.photo_btn": "拍照",
        "insurance.upload_btn": "上传",

        "incident.title": "描述您的情况",
        "incident.subtitle": "告诉我们发生了什么以及您需要什么样的护理。",
        "incident.emergency_alert": "这可能是危及生命的紧急情况",
        "incident.emergency_action": "如果感觉紧急，请立即拨打 911。",
        "incident.description": "发生了什么？",
        "incident.description_placeholder": "简要描述您的情况或受伤...",
        "incident.care_type": "所需护理类型",
        "incident.symptoms": "症状",
        "incident.symptoms_hint": "选择所有适用的症状，以便我们评估您需要的医院能力。",
        "incident.severity": "情况有多严重？",

        "results.insurance": "保险:",
        "results.care": "护理:",
        "results.location_placeholder": "输入位置 (例如: Midtown)",
        "results.use_gps": "使用 GPS",
        "results.locating": "定位中...",
        "results.sort.closest": "距离最近",
        "results.sort.best_match": "最佳保险匹配",
        "results.sort.lowest_cost": "最低费用",
        "results.show_map": "显示地图",
        "results.list_only": "仅列表",
        "results.filters": "筛选",
        "results.filter.capability": "能力",
        "results.filter.insurance": "保险状态",
        "results.filter.distance": "最大距离",
        "results.filter.clear": "清除所有筛选",
        "results.finding": "正在查找医院...",
        "results.no_results": "未找到医院",
        "results.no_results_hint": "尝试增加距离或清除一些筛选条件。",

        "hospital.view_details": "查看详情",
        "hospital.call": "呼叫医院",
        "hospital.est_cost": "预估费用",
        "hospital.distance": "距离",
        "hospital.insurance": "保险",
        "hospital.verified": "已验证",
        "hospital.out_of_network": "网络外",
        "hospital.unknown_coverage": "覆盖范围未知",

        "care_type.emergency": "急诊室 (ER)",
        "care_type.urgent": "紧急护理",
        "care_type.not-sure": "不确定",
        "care_desc.emergency": "危及生命或需要立即关注的严重情况",
        "care_desc.urgent": "非危及生命但需要今天及时医疗护理的情况",
        "care_desc.not-sure": "我们将根据您的症状和严重程度帮助匹配",

        "symptom.chest-pain": "胸痛",
        "symptom.stroke": "中风症状",
        "symptom.major-bleeding": "大出血",
        "symptom.broken-bone": "骨折",
        "symptom.severe-burn": "严重烧伤",
        "symptom.allergic-reaction": "过敏反应",
        "symptom.high-fever": "高烧",
        "symptom.head-injury": "头部受伤",
        "symptom.other": "其他 / 不确定",

        "severity.mild": "轻微",
        "severity.moderate": "中度",
        "severity.severe": "严重",
        "severity_desc.mild": "可控，未恶化",
        "severity_desc.moderate": "显著但稳定",
        "severity_desc.severe": "剧烈，快速恶化",
    },
    ru: {
        "app.title": "CareNet",
        "search.placeholder": "Поиск больниц, специальностей...",
        "mode.all": "Все",
        "mode.emergency": "Скорая",
        "mode.urgent_care": "Неотложная помощь",
        "nav.profile": "Профиль",
        "nav.signout": "Выйти",
        "triage.title": "Опишите ситуацию",
        "triage.subtitle": "Расскажите, что случилось и какая помощь нужна.",
        "triage.voice_btn": "Голосовой ИИ",
        "triage.manual_btn": "Вручную",
        "triage.listening": "Слушаю...",
        "triage.analyzing": "Анализ...",
        "triage.stop": "Стоп и анализ",
        "triage.try_again": "Попробовать снова",
        "triage.apply": "Применить",
        "footer.disclaimer": "Не медицинский совет · При ЧП звоните 911",

        "triage.start_speaking": "Начать говорить",
        "triage.voice_instruction": "Опишите симптомы голосом",
        "triage.voice_subtext": "Нажмите кнопку и опишите, что случилось. Наш ИИ определит категорию и порекомендует помощь.",

        "insurance.title": "Данные страховки",
        "insurance.subtitle": "Помогает оценить покрытие и расходы.",
        "insurance.privacy": "Данные хранятся только на вашем устройстве.",
        "insurance.quick_scan": "Скан",
        "insurance.fastest": "Быстро",
        "insurance.or_manual": "Или вручную",
        "insurance.provider": "Страховщик",
        "insurance.provider_placeholder": "Выберите страховщика",
        "insurance.plan_type": "Тип плана",
        "insurance.plan_type_placeholder": "Выберите план",
        "insurance.network": "Название сети",
        "insurance.optional": "(необязательно)",
        "insurance.network_hint": "На лицевой стороне карты",
        "insurance.zip": "Индекс (ZIP)",
        "insurance.zip_hint": "Для уточнения покрытия",
        "insurance.prefer_network": "Только в сети",
        "insurance.prefer_network_hint": "Показывать только подтвержденные больницы",
        "insurance.back": "Назад",
        "insurance.continue": "Далее",

        "insurance.scan_title": "Сканировать карту",
        "insurance.scan_subtitle": "Сделайте фото или загрузите",
        "insurance.photo_btn": "Фото",
        "insurance.upload_btn": "Загрузить",

        "incident.title": "Опишите ситуацию",
        "incident.subtitle": "Расскажите, что случилось.",
        "incident.emergency_alert": "Возможна угроза жизни",
        "incident.emergency_action": "Если срочно, звоните 911.",
        "incident.description": "Что произошло?",
        "incident.description_placeholder": "Кратко опишите ситуацию...",
        "incident.care_type": "Тип помощи",
        "incident.symptoms": "Симптомы",
        "incident.symptoms_hint": "Выберите все подходящие.",
        "incident.severity": "Насколько серьезно?",

        "results.insurance": "Страховка:",
        "results.care": "Помощь:",
        "results.location_placeholder": "Ваше местоположение",
        "results.use_gps": "GPS",
        "results.locating": "Поиск...",
        "results.sort.closest": "Ближайшие",
        "results.sort.best_match": "Лучшее совпадение",
        "results.sort.lowest_cost": "Дешевле",
        "results.show_map": "Карта",
        "results.list_only": "Список",
        "results.filters": "Фильтры",
        "results.filter.capability": "Возможности",
        "results.filter.insurance": "Статус страховки",
        "results.filter.distance": "Макс. дистанция",
        "results.filter.clear": "Очистить",
        "results.finding": "Поиск больниц...",
        "results.no_results": "Больницы не найдены",
        "results.no_results_hint": "Попробуйте увеличить радиус.",

        "hospital.view_details": "Подробнее",
        "hospital.call": "Позвонить",
        "hospital.est_cost": "СТОИМОСТЬ",
        "hospital.distance": "РАССТОЯНИЕ",
        "hospital.insurance": "СТРАХОВКА",
        "hospital.verified": "Подтверждено",
        "hospital.out_of_network": "Вне сети",
        "hospital.unknown_coverage": "Неизвестно",

        "care_type.emergency": "Скорая (ER)",
        "care_type.urgent": "Неотложная помощь",
        "care_type.not-sure": "Не уверен",
        "care_desc.emergency": "Угроза жизни, требует немедленного внимания",
        "care_desc.urgent": "Не угрожает жизни, но нужна помощь сегодня",
        "care_desc.not-sure": "Мы поможем выбрать на основе симптомов",

        "symptom.chest-pain": "Боль в груди",
        "symptom.stroke": "Симптомы инсульта",
        "symptom.major-bleeding": "Сильное кровотечение",
        "symptom.broken-bone": "Перелом",
        "symptom.severe-burn": "Сильный ожог",
        "symptom.allergic-reaction": "Аллергия",
        "symptom.high-fever": "Высокая температура",
        "symptom.head-injury": "Травма головы",
        "symptom.other": "Другое",

        "severity.mild": "Легкая",
        "severity.moderate": "Средняя",
        "severity.severe": "Тяжелая",
        "severity_desc.mild": "Терпимо, не хуже",
        "severity_desc.moderate": "Значительная, но стабильно",
        "severity_desc.severe": "Интенсивная, быстро хуже",
    },
    bn: {
        "app.title": "CareNet",
        "search.placeholder": "হাসপাতাল খুঁজুন...",
        "mode.all": "সব",
        "mode.emergency": "জরুরী অবস্থা",
        "mode.urgent_care": "জরুরী যত্ন",
        "nav.profile": "আমার প্রোফাইল",
        "nav.signout": "লগ আউট",
        "triage.title": "আপনার পরিস্থিতি বর্ণনা করুন",
        "triage.subtitle": "আমাদের বলুন কি হয়েছে এবং আপনার কি ধরনের সেবা প্রয়োজন।",
        "triage.voice_btn": "AI ভয়েস ট্রিজে",
        "triage.manual_btn": "ম্যানুয়াল এন্ট্রি",
        "triage.listening": "শুনছি...",
        "triage.analyzing": "বিশ্লেষণ করা হচ্ছে...",
        "triage.stop": "থামুন এবং বিশ্লেষণ করুন",
        "triage.try_again": "আবার চেষ্টা করুন",
        "triage.apply": "প্রয়োগ করুন",
        "footer.disclaimer": "চিকিৎসা পরামর্শ নয় · জরুরী অবস্থার জন্য 911 কল করুন",

        "triage.start_speaking": "কথা বলা শুরু করুন",
        "triage.voice_instruction": "আপনার লক্ষণগুলি বর্ণনা করুন",
        "triage.voice_subtext": "বোতাম টিপুন এবং বর্ণনা করুন। আমাদের এআই আপনার আঘাতের ধরন এবং প্রয়োজনীয় যত্ন সুপারিশ করবে।",

        "insurance.title": "আপনার বীমা বিবরণ",
        "insurance.subtitle": "এটি কভারেজ এবং খরচ অনুমান করতে সাহায্য করে।",
        "insurance.privacy": "আপনার তথ্য শুধুমাত্র আপনার ডিভাইসে থাকে।",
        "insurance.quick_scan": "দ্রুত স্ক্যান",
        "insurance.fastest": "দ্রুততম",
        "insurance.or_manual": "অথবা ম্যানুয়ালি লিখুন",
        "insurance.provider": "বীমা প্রদানকারী",
        "insurance.provider_placeholder": "প্রদানকারী নির্বাচন করুন",
        "insurance.plan_type": "পরিকল্পনার ধরন",
        "insurance.plan_type_placeholder": "পরিকল্পনা নির্বাচন করুন",
        "insurance.network": "নেটওয়ার্কের নাম",
        "insurance.optional": "(ঐচ্ছিক)",
        "insurance.network_hint": "আপনার কার্ডের সামনে পাওয়া যাবে",
        "insurance.zip": "জিপ কোড",
        "insurance.zip_hint": "নেটওয়ার্ক কভারেজ সংকীর্ণ করতে সাহায্য করে",
        "insurance.prefer_network": "শুধুমাত্র নেটওয়ার্ক-এর মধ্যে",
        "insurance.prefer_network_hint": "শুধুমাত্র আপনার পরিকল্পনা গ্রহণকারী হাসপাতাল দেখান",
        "insurance.back": "পেছনে",
        "insurance.continue": "চালিয়ে যান",

        "insurance.scan_title": "বীমা কার্ড স্ক্যান করুন",
        "insurance.scan_subtitle": "ছবি তুলুন বা আপলোড করুন",
        "insurance.photo_btn": "ছবি",
        "insurance.upload_btn": "আপলোড",

        "incident.title": "পরিস্থিতি বর্ণনা করুন",
        "incident.subtitle": "আমাদের বলুন কি হয়েছে।",
        "incident.emergency_alert": "এটি একটি জীবন-হুমকিপূর্ণ জরুরী অবস্থা হতে পারে",
        "incident.emergency_action": "জরুরী মনে হলে অবিলম্বে 911 কল করুন।",
        "incident.description": "কি হয়েছে?",
        "incident.description_placeholder": "সংক্ষেপে বর্ণনা করুন...",
        "incident.care_type": "কি ধরনের যত্ন প্রয়োজন",
        "incident.symptoms": "লক্ষণসমূহ",
        "incident.symptoms_hint": "সব প্রযোজ্য নির্বাচন করুন।",
        "incident.severity": "পরিস্থিতি কতটা গুরুতর?",

        "results.insurance": "বীমা:",
        "results.care": "যত্ন:",
        "results.location_placeholder": "অবস্থান লিখুন",
        "results.use_gps": "GPS ব্যবহার করুন",
        "results.locating": "খোঁজা হচ্ছে...",
        "results.sort.closest": "নিকটতম",
        "results.sort.best_match": "সেরা মিল",
        "results.sort.lowest_cost": "সবচেয়ে কম খরচ",
        "results.show_map": "মানচিত্র দেখান",
        "results.list_only": "শুধুমাত্র তালিকা",
        "results.filters": "ফিল্টার",
        "results.filter.capability": "ক্ষমতা",
        "results.filter.insurance": "বীমা অবস্থা",
        "results.filter.distance": "সর্বোচ্চ দূরত্ব",
        "results.filter.clear": "ফিল্টার মুছুন",
        "results.finding": "হাসপাতাল খোঁজা হচ্ছে...",
        "results.no_results": "কোন হাসপাতাল পাওয়া যায়নি",
        "results.no_results_hint": "দূরত্ব বাড়ানোর চেষ্টা করুন।",

        "hospital.view_details": "বিস্তারিত দেখুন",
        "hospital.call": "হাসপাতালে কল করুন",
        "hospital.est_cost": "আনুমানিক ব্যয়",
        "hospital.distance": "দূরত্ব",
        "hospital.insurance": "বীমা",
        "hospital.verified": "যাচাইকৃত",
        "hospital.out_of_network": "নেটওয়ার্কের বাইরে",
        "hospital.unknown_coverage": "অজানা কভারেজ",

        "care_type.emergency": "জরুরী কক্ষ (ER)",
        "care_type.urgent": "জরুরী যত্ন",
        "care_type.not-sure": "নিশ্চিত নই",
        "care_desc.emergency": "জীবন-হুমকিপূর্ণ বা গুরুতর অবস্থা",
        "care_desc.urgent": "জীবন-হুমকিপূর্ণ নয় কিন্তু আজই চিকিৎসা প্রয়োজন",
        "care_desc.not-sure": "আমরা লক্ষণের ভিত্তিতে সাহায্য করব",

        "symptom.chest-pain": "বুকে ব্যথা",
        "symptom.stroke": "স্ট্রোকের লক্ষণ",
        "symptom.major-bleeding": "অতিরিক্ত রক্তপাত",
        "symptom.broken-bone": "হাড় ভাঙা",
        "symptom.severe-burn": "গুরুতর পোড়া",
        "symptom.allergic-reaction": "এলার্জি প্রতিক্রিয়া",
        "symptom.high-fever": "উচ্চ জ্বর",
        "symptom.head-injury": "মাথায় আঘাত",
        "symptom.other": "অন্যান্য / নিশ্চিত নই",

        "severity.mild": "মৃদু",
        "severity.moderate": "মাঝারি",
        "severity.severe": "গুরুতর",
        "severity_desc.mild": "নিয়ন্ত্রণযোগ্য",
        "severity_desc.moderate": "উল্লেখযোগ্য কিন্তু স্থিতিশীল",
        "severity_desc.severe": "তীব্র, দ্রুত খারাপ হচ্ছে",
    },
    ht: {
        "app.title": "CareNet",
        "search.placeholder": "Chèche lopital...",
        "mode.all": "Tout",
        "mode.emergency": "Ijans",
        "mode.urgent_care": "Swen Ijan",
        "nav.profile": "Pwofil Mwen",
        "nav.signout": "Dekonekte",
        "triage.title": "Dekri sitiyasyon ou",
        "triage.subtitle": "Di nou kisa ki pase ak ki kalite swen ou bezwen.",
        "triage.voice_btn": "AI Vwa Triye",
        "triage.manual_btn": "Antre Manyèl",
        "triage.listening": "N ap koute...",
        "triage.analyzing": "N ap analize...",
        "triage.stop": "Sispann ak analize",
        "triage.try_again": "Eseye ankò",
        "triage.apply": "Aplike",
        "footer.disclaimer": "Se pa konsèy medikal · Rele 911 pou ijans",

        "triage.start_speaking": "Kòmanse pale",
        "triage.voice_instruction": "Dekri sentòm ou yo",
        "triage.voice_subtext": "Peze bouton an epi eksplike sa k pase. AI nou an ap ede jwenn bon swen an pou ou.",

        "insurance.title": "Detay Asirans Ou",
        "insurance.subtitle": "Sa ede nou estime depans nan chak lopital.",
        "insurance.privacy": "Done ou yo rete sou aparèy ou an.",
        "insurance.quick_scan": "Eskane vit",
        "insurance.fastest": "Pi vit",
        "insurance.or_manual": "Oswa antre manyèlman",
        "insurance.provider": "Konpayi Asirans",
        "insurance.provider_placeholder": "Chwazi konpayi",
        "insurance.plan_type": "Kalite Plan",
        "insurance.plan_type_placeholder": "Chwazi plan",
        "insurance.network": "Non Rezo a",
        "insurance.optional": "(opsyonèl)",
        "insurance.network_hint": "Sou devan kat ou a",
        "insurance.zip": "Kòd Postal",
        "insurance.zip_hint": "Ede jwenn kouvèti lokal",
        "insurance.prefer_network": "Nan rezo sèlman",
        "insurance.prefer_network_hint": "Montre sèlman lopital ki aksepte plan ou",
        "insurance.back": "Tounen",
        "insurance.continue": "Kontinye",

        "insurance.scan_title": "Eskane kat asirans",
        "insurance.scan_subtitle": "Pran yon foto oswa telechaje",
        "insurance.photo_btn": "Foto",
        "insurance.upload_btn": "Telechaje",

        "incident.title": "Dekri sitiyasyon an",
        "incident.subtitle": "Di nou kisa ki pase.",
        "incident.emergency_alert": "Sa ka yon ijans ki menase lavi",
        "incident.emergency_action": "Si li ijan, rele 911 imedyatman.",
        "incident.description": "Kisa ki pase?",
        "incident.description_placeholder": "Dekri sitiyasyon an...",
        "incident.care_type": "Kalite swen",
        "incident.symptoms": "Sentòm",
        "incident.symptoms_hint": "Chwazi tout sa ki aplike.",
        "incident.severity": "Ki jan sa grav?",

        "results.insurance": "Asirans:",
        "results.care": "Swen:",
        "results.location_placeholder": "Antre kote ou ye",
        "results.use_gps": "Sèvi ak GPS",
        "results.locating": "N ap chèche...",
        "results.sort.closest": "Pi pre",
        "results.sort.best_match": "Pi bon matche",
        "results.sort.lowest_cost": "Pi bon pri",
        "results.show_map": "Kat jeyografik",
        "results.list_only": "Lis sèlman",
        "results.filters": "Filtè",
        "results.filter.capability": "Kapasite",
        "results.filter.insurance": "Eta Asirans",
        "results.filter.distance": "Distans Maks",
        "results.filter.clear": "Efase filtè",
        "results.finding": "N ap chèche lopital...",
        "results.no_results": "Pa gen lopital",
        "results.no_results_hint": "Eseye ogmante distans la.",

        "hospital.view_details": "Gade detay",
        "hospital.call": "Rele Lopital",
        "hospital.est_cost": "PRI ESTIMASYON",
        "hospital.distance": "DISTANS",
        "hospital.insurance": "ASIRANS",
        "hospital.verified": "Verifye",
        "hospital.out_of_network": "Pa nan rezo",
        "hospital.unknown_coverage": "Kouvèti enkoni",

        "care_type.emergency": "Ijans (ER)",
        "care_type.urgent": "Swen Ijan",
        "care_type.not-sure": "Pa sèten",
        "care_desc.emergency": "Kondisyon grav ki bezwen swen touswit",
        "care_desc.urgent": "Pa yon ijans lavi men bezwen swen jodia",
        "care_desc.not-sure": "N ap ede ou chwazi baz sou sentòm ou yo",

        "symptom.chest-pain": "Doule nan pwatrin",
        "symptom.stroke": "Sentòm konjesyon serebral",
        "symptom.major-bleeding": "Gwo senyen",
        "symptom.broken-bone": "Zo kase",
        "symptom.severe-burn": "Gwo boule",
        "symptom.allergic-reaction": "Reyaksyon alèjik",
        "symptom.high-fever": "Gwo lafyèv",
        "symptom.head-injury": "Chòk nan tèt",
        "symptom.other": "Lòt / Pa sèten",

        "severity.mild": "Lejè",
        "severity.moderate": "Modere",
        "severity.severe": "Grav",
        "severity_desc.mild": "Jere, pa vin pi mal",
        "severity_desc.moderate": "Enpòtan men ki estab",
        "severity_desc.severe": "Entans, vin pi mal vit",
    },
    ko: {
        "app.title": "CareNet",
        "search.placeholder": "병원 검색...",
        "mode.all": "전체",
        "mode.emergency": "응급",
        "mode.urgent_care": "긴급 치료",
        "nav.profile": "내 프로필",
        "nav.signout": "로그아웃",
        "triage.title": "상황을 설명해주세요",
        "triage.subtitle": "무슨 일이 있었는지, 어떤 치료가 필요한지 알려주세요.",
        "triage.voice_btn": "AI 음성 분류",
        "triage.manual_btn": "직접 입력",
        "triage.listening": "듣고 있습니다...",
        "triage.analyzing": "분석 중...",
        "triage.stop": "중지 및 분석",
        "triage.try_again": "다시 시도",
        "triage.apply": "적용하기",
        "footer.disclaimer": "의학적 조언이 아닙니다 · 응급 상황 시 911",

        "triage.start_speaking": "말하기 시작",
        "triage.voice_instruction": "증상을 말로 설명하세요",
        "triage.voice_subtext": "버튼을 누르고 증상을 설명하세요. AI가 부상을 분류하고 적절한 치료를 추천합니다.",

        "insurance.title": "보험 상세 정보",
        "insurance.subtitle": "보장 범위와 본인 부담금을 추정하는 데 도움이 됩니다.",
        "insurance.privacy": "데이터는 기기에만 저장됩니다.",
        "insurance.quick_scan": "빠른 스캔",
        "insurance.fastest": "가장 빠름",
        "insurance.or_manual": "또는 직접 입력",
        "insurance.provider": "보험사",
        "insurance.provider_placeholder": "보험사 선택",
        "insurance.plan_type": "플랜 유형",
        "insurance.plan_type_placeholder": "플랜 선택",
        "insurance.network": "네트워크 이름",
        "insurance.optional": "(선택)",
        "insurance.network_hint": "보험 카드 앞면에 있습니다",
        "insurance.zip": "우편번호",
        "insurance.zip_hint": "네트워크 범위를 좁히는 데 도움",
        "insurance.prefer_network": "네트워크 내 병원만",
        "insurance.prefer_network_hint": "보장되는 병원만 표시",
        "insurance.back": "뒤로",
        "insurance.continue": "계속",

        "insurance.scan_title": "보험 카드 스캔",
        "insurance.scan_subtitle": "사진 촬영 또는 업로드",
        "insurance.photo_btn": "사진",
        "insurance.upload_btn": "업로드",

        "incident.title": "상황 설명",
        "incident.subtitle": "무슨 일이 있었나요?",
        "incident.emergency_alert": "생명을 위협하는 응급 상황일 수 있습니다",
        "incident.emergency_action": "위급하다면 즉시 911에 전화하세요.",
        "incident.description": "무슨 일이 있었나요?",
        "incident.description_placeholder": "간단히 설명해주세요...",
        "incident.care_type": "필요한 치료 유형",
        "incident.symptoms": "증상",
        "incident.symptoms_hint": "해당되는 모든 항목을 선택하세요.",
        "incident.severity": "심각도",

        "results.insurance": "보험:",
        "results.care": "치료:",
        "results.location_placeholder": "위치 입력",
        "results.use_gps": "GPS 사용",
        "results.locating": "위치 확인 중...",
        "results.sort.closest": "거리순",
        "results.sort.best_match": "보험 매칭순",
        "results.sort.lowest_cost": "비용순",
        "results.show_map": "지도 보기",
        "results.list_only": "목록만 보기",
        "results.filters": "필터",
        "results.filter.capability": "진료 가능",
        "results.filter.insurance": "보험 상태",
        "results.filter.distance": "최대 거리",
        "results.filter.clear": "필터 초기화",
        "results.finding": "병원 검색 중...",
        "results.no_results": "병원을 찾을 수 없습니다",
        "results.no_results_hint": "거리를 늘려보세요.",

        "hospital.view_details": "상세 보기",
        "hospital.call": "병원 전화하기",
        "hospital.est_cost": "예상 비용",
        "hospital.distance": "거리",
        "hospital.insurance": "보험",
        "hospital.verified": "확인됨",
        "hospital.out_of_network": "네트워크 외",
        "hospital.unknown_coverage": "보장 미확인",

        "care_type.emergency": "응급실 (ER)",
        "care_type.urgent": "긴급 치료",
        "care_type.not-sure": "잘 모름",
        "care_desc.emergency": "즉각적인 치료가 필요한 심각한 상태",
        "care_desc.urgent": "생명 위협은 없으나 오늘 치료 필요",
        "care_desc.not-sure": "증상에 따라 안내해 드립니다",

        "symptom.chest-pain": "흉통",
        "symptom.stroke": "뇌졸중 증상",
        "symptom.major-bleeding": "심한 출혈",
        "symptom.broken-bone": "골절",
        "symptom.severe-burn": "심한 화상",
        "symptom.allergic-reaction": "알레르기 반응",
        "symptom.high-fever": "고열",
        "symptom.head-injury": "머리 부상",
        "symptom.other": "기타 / 불확실",

        "severity.mild": "경미",
        "severity.moderate": "중등도",
        "severity.severe": "심각",
        "severity_desc.mild": "관리 가능, 악화되지 않음",
        "severity_desc.moderate": "상당하지만 안정적",
        "severity_desc.severe": "극심함, 빠르게 악화",
    },
    ar: {
        "app.title": "CareNet",
        "search.placeholder": "البحث عن المستشفيات...",
        "mode.all": "الكل",
        "mode.emergency": "طوارئ",
        "mode.urgent_care": "رعاية عاجلة",
        "nav.profile": "ملفي الشخصي",
        "nav.signout": "تسجيل خروج",
        "triage.title": "وصف الحالة",
        "triage.subtitle": "أخبرنا ماذا حدث وما نوع الرعاية التي تحتاجها.",
        "triage.voice_btn": "التصنيف الصوتي بالذكاء الاصطناعي",
        "triage.manual_btn": "إدخال يدوي",
        "triage.listening": "جاري الاستماع...",
        "triage.analyzing": "جاري التحليل...",
        "triage.stop": "توقف وتحليل",
        "triage.try_again": "حاول مرة أخرى",
        "triage.apply": "تطبيق",
        "footer.disclaimer": "ليست نصيحة طبية · للطوارئ اتصل بـ 911",

        "triage.start_speaking": "ابدأ التحدث",
        "triage.voice_instruction": "صِف أعراضك بالصوت",
        "triage.voice_subtext": "اضغط على الزر واشرح ما حدث. سيقوم الذكاء الاصطناعي بتصنيف إصابتك والتوصية بالرعاية المناسبة.",

        "insurance.title": "تفاصيل التأمين",
        "insurance.subtitle": "يساعدنا في تقدير التغطية والتكاليف.",
        "insurance.privacy": "تظل بياناتك على جهازك فقط.",
        "insurance.quick_scan": "مسح سريع",
        "insurance.fastest": "الأسرع",
        "insurance.or_manual": "أو أدخل يدوياً",
        "insurance.provider": "شركة التأمين",
        "insurance.provider_placeholder": "اختر المزود",
        "insurance.plan_type": "نوع الخطة",
        "insurance.plan_type_placeholder": "اختر الخطة",
        "insurance.network": "اسم الشبكة",
        "insurance.optional": "(اختياري)",
        "insurance.network_hint": "موجود على واجهة البطاقة",
        "insurance.zip": "الرمز البريدي",
        "insurance.zip_hint": "للمساعدة في تحديد النطاق",
        "insurance.prefer_network": "داخل الشبكة فقط",
        "insurance.prefer_network_hint": "إظهار المستشفيات التي تقبل خطتك فقط",
        "insurance.back": "رجوع",
        "insurance.continue": "متابعة",

        "insurance.scan_title": "مسح بطاقة التأمين",
        "insurance.scan_subtitle": "التقط صورة أو حملها",
        "insurance.photo_btn": "صورة",
        "insurance.upload_btn": "تحميل",

        "incident.title": "وصف الموقف",
        "incident.subtitle": "أخبرنا ماذا حدث.",
        "incident.emergency_alert": "قد تكون هذه حالة طارئة مهددة للحياة",
        "incident.emergency_action": "إذا كان الأمر عاجلاً، اتصل بـ 911 فوراً.",
        "incident.description": "ماذا حدث؟",
        "incident.description_placeholder": "وصف مختصر...",
        "incident.care_type": "نوع الرعاية",
        "incident.symptoms": "الأعراض",
        "incident.symptoms_hint": "حدد كل ما ينطبق.",
        "incident.severity": "ما مدى الخطورة؟",

        "results.insurance": "التأمين:",
        "results.care": "الرعاية:",
        "results.location_placeholder": "أدخل الموقع",
        "results.use_gps": "استخدم GPS",
        "results.locating": "تحديد الموقع...",
        "results.sort.closest": "الأقرب",
        "results.sort.best_match": "الأفضل تأميناً",
        "results.sort.lowest_cost": "الأقل تكلفة",
        "results.show_map": "عرض الخريطة",
        "results.list_only": "قائمة فقط",
        "results.filters": "تصفية",
        "results.filter.capability": "الإمكانيات",
        "results.filter.insurance": "حالة التأمين",
        "results.filter.distance": "أقصى مسافة",
        "results.filter.clear": "مسح التصفيات",
        "results.finding": "البحث عن مستشفيات...",
        "results.no_results": "لم يتم العثور على مستشفيات",
        "results.no_results_hint": "حاول زيادة المسافة.",

        "hospital.view_details": "عرض التفاصيل",
        "hospital.call": "اتصل بالمستشفى",
        "hospital.est_cost": "التكلفة التقديرية",
        "hospital.distance": "المسافة",
        "hospital.insurance": "تأمين",
        "hospital.verified": "مؤكد",
        "hospital.out_of_network": "خارج الشبكة",
        "hospital.unknown_coverage": "تغطية غير معروفة",

        "care_type.emergency": "طوارئ (ER)",
        "care_type.urgent": "رعاية عاجلة",
        "care_type.not-sure": "غير متأكد",
        "care_desc.emergency": "حالة خطيرة تتطلب عناية فورية",
        "care_desc.urgent": "ليست مهددة للحياة لكن تحتاج رعاية اليوم",
        "care_desc.not-sure": "سنساعدك في الاختيار",

        "symptom.chest-pain": "ألم الصدر",
        "symptom.stroke": "أعراض السكتة الدماغية",
        "symptom.major-bleeding": "نزيف حاد",
        "symptom.broken-bone": "كسر عظم",
        "symptom.severe-burn": "حروق شديدة",
        "symptom.allergic-reaction": "حساسية شديدة",
        "symptom.high-fever": "حمي عالية",
        "symptom.head-injury": "إصابة الرأس",
        "symptom.other": "أخرى / غير متأكد",

        "severity.mild": "طيف",
        "severity.moderate": "متوسط",
        "severity.severe": "شديد",
        "severity_desc.mild": "يمكن التحكم به",
        "severity_desc.moderate": "ملحوظ لكن مستقر",
        "severity_desc.severe": "مكثف، يزداد سوءاً",
    },
    fr: {
        "app.title": "CareNet",
        "search.placeholder": "Rechercher...",
        "mode.all": "Tout",
        "mode.emergency": "Urgences",
        "mode.urgent_care": "Soins Urgents",
        "nav.profile": "Mon Profil",
        "nav.signout": "Se déconnecter",
        "triage.title": "Décrivez votre situation",
        "triage.subtitle": "Dites-nous ce qui s'est passé et de quels soins vous avez besoin.",
        "triage.voice_btn": "Triage Vocal IA",
        "triage.manual_btn": "Saisie Manuelle",
        "triage.listening": "Écoute...",
        "triage.analyzing": "Analyse...",
        "triage.stop": "Arrêter et analyser",
        "triage.try_again": "Réessayer",
        "triage.apply": "Appliquer",
        "footer.disclaimer": "Pas un avis médical · Pour urgences 911",

        "triage.start_speaking": "Commencer à parler",
        "triage.voice_instruction": "Décrivez vos symptômes",
        "triage.voice_subtext": "Appuyez sur le bouton et décrivez ce qui s'est passé. Notre IA recommandera les soins appropriés.",

        "insurance.title": "Détails d'assurance",
        "insurance.subtitle": "Aide à estimer la couverture et les coûts.",
        "insurance.privacy": "Vos données restent sur votre appareil.",
        "insurance.quick_scan": "Scan rapide",
        "insurance.fastest": "Le plus rapide",
        "insurance.or_manual": "Ou saisie manuelle",
        "insurance.provider": "Assureur",
        "insurance.provider_placeholder": "Sélectionner",
        "insurance.plan_type": "Type de plan",
        "insurance.plan_type_placeholder": "Sélectionner",
        "insurance.network": "Réseau",
        "insurance.optional": "(optionnel)",
        "insurance.network_hint": "Sur votre carte",
        "insurance.zip": "Code postal",
        "insurance.zip_hint": "Précise la couverture",
        "insurance.prefer_network": "Réseau uniquement",
        "insurance.prefer_network_hint": "Uniquement les hôpitaux couverts",
        "insurance.back": "Retour",
        "insurance.continue": "Continuer",

        "insurance.scan_title": "Scanner carte d'assurance",
        "insurance.scan_subtitle": "Prendre une photo ou télécharger",
        "insurance.photo_btn": "Photo",
        "insurance.upload_btn": "Télécharger",

        "incident.title": "Décrivez votre situation",
        "incident.subtitle": "Dites-nous ce qui s'est passé.",
        "incident.emergency_alert": "Urgence potentielle menaçant la vie",
        "incident.emergency_action": "Appelez le 911 immédiatement.",
        "incident.description": "Que s'est-il passé ?",
        "incident.description_placeholder": "Décrivez brièvement...",
        "incident.care_type": "Type de soins",
        "incident.symptoms": "Symptômes",
        "incident.symptoms_hint": "Sélectionnez tout ce qui s'applique.",
        "incident.severity": "Gravité ?",

        "results.insurance": "Assurance:",
        "results.care": "Soins:",
        "results.location_placeholder": "Lieu (ex: Midtown)",
        "results.use_gps": "Utiliser GPS",
        "results.locating": "Localisation...",
        "results.sort.closest": "Plus proche",
        "results.sort.best_match": "Meilleur match",
        "results.sort.lowest_cost": "Moins cher",
        "results.show_map": "Carte",
        "results.list_only": "Liste",
        "results.filters": "Filtres",
        "results.filter.capability": "Capacité",
        "results.filter.insurance": "Statut assurance",
        "results.filter.distance": "Dist. max",
        "results.filter.clear": "Effacer",
        "results.finding": "Recherche...",
        "results.no_results": "Aucun hôpital",
        "results.no_results_hint": "Augmentez la distance.",

        "hospital.view_details": "Voir détails",
        "hospital.call": "Appeler",
        "hospital.est_cost": "COÛT EST.",
        "hospital.distance": "EL.",
        "hospital.insurance": "ASSURANCE",
        "hospital.verified": "Vérifié",
        "hospital.out_of_network": "Hors Réseau",
        "hospital.unknown_coverage": "Inconnu",

        "care_type.emergency": "Urgences (ER)",
        "care_type.urgent": "Soins Urgents",
        "care_type.not-sure": "Pas sûr",
        "care_desc.emergency": "Condition grave nécessitant une attention immédiate",
        "care_desc.urgent": "Pas vital mais nécessite des soins aujourd'hui",
        "care_desc.not-sure": "Nous vous aiderons à choisir selon vos symptômes",

        "symptom.chest-pain": "Douleur thoracique",
        "symptom.stroke": "Symptômes AVC",
        "symptom.major-bleeding": "Saignement important",
        "symptom.broken-bone": "Os brisé",
        "symptom.severe-burn": "Brûlure grave",
        "symptom.allergic-reaction": "Réaction allergique",
        "symptom.high-fever": "Fidèvre élevée",
        "symptom.head-injury": "Blessure à la tête",
        "symptom.other": "Autre / Pas sûr",

        "severity.mild": "Léger",
        "severity.moderate": "Modéré",
        "severity.severe": "Grave",
        "severity_desc.mild": "Gérable, ne s'aggrave pas",
        "severity_desc.moderate": "Significatif mais stable",
        "severity_desc.severe": "Intense, s'aggrave vite",
    },
    ur: {
        "app.title": "CareNet",
        "search.placeholder": "ہسپताल تلاش کریں...",
        "mode.all": "تمام",
        "mode.emergency": "ایمرجنسی",
        "mode.urgent_care": "فوری دیکھ بھال",
        "nav.profile": "میرا پروفائل",
        "nav.signout": "سائن آؤٹ",
        "triage.title": "اپنی صورتحال بیان کریں",
        "triage.subtitle": "ہمیں بتائیں کہ کیا ہوا اور آپ کو کس قسم کی دیکھ بھال کی ضرورت ہے۔",
        "triage.voice_btn": "AI وائس ٹriage",
        "triage.manual_btn": "دستی اندراج",
        "triage.listening": "سن رہا ہے...",
        "triage.analyzing": "تجزیہ کر رہا ہے...",
        "triage.stop": "روکیں اور تجزیہ کریں",
        "triage.try_again": "دوبارہ کوشش کریں",
        "triage.apply": "لاگو کریں",
        "footer.disclaimer": "طبی مشورہ نہیں · ایمرجنسی کے لیے 911 کال کریں",

        "triage.start_speaking": "بولنا شروع کریں",
        "triage.voice_instruction": "اپنی علامات بیان کریں",
        "triage.voice_subtext": "بٹن دبائیں اور بیان کریں۔ ہمارا AI آپ کی چوٹ کی درجہ بندی کرے گا اور صحیح دیکھ بھال کی سفارش کرے گا۔",

        "insurance.title": "انشورنس کی تفصیلات",
        "insurance.subtitle": "یہ ہمیں کوریج اور اخراجات کا اندازہ لگانے میں مدد کرتا ہے۔",
        "insurance.privacy": "آپ کا ڈیٹا صرف آپ کے آلے پر رہتا ہے۔",
        "insurance.quick_scan": "فوری اسکین",
        "insurance.fastest": "سب سے تیز",
        "insurance.or_manual": "یا دستی طور پر درج کریں",
        "insurance.provider": "انشورنس فراہم کنندہ",
        "insurance.provider_placeholder": "فراہم کنندہ منتخب کریں",
        "insurance.plan_type": "پلان کی قسم",
        "insurance.plan_type_placeholder": "پلان منتخب کریں",
        "insurance.network": "نیٹ ورک کا نام",
        "insurance.optional": "(اختیاری)",
        "insurance.network_hint": "کارڈ کے سامنے",
        "insurance.zip": "زپ کوڈ",
        "insurance.zip_hint": "کوریج تلاش کرنے میں مدد کرتا ہے",
        "insurance.prefer_network": "صرف نیٹ ورک میں",
        "insurance.prefer_network_hint": "صرف وہ ہسپتال دکھائیں جو آپ کا پلان قبول کرتے ہیں",
        "insurance.back": "واپس",
        "insurance.continue": "جاری رکھیں",

        "insurance.scan_title": "انشورنس کارڈ اسکین کریں",
        "insurance.scan_subtitle": "تصویر لیں یا اپ لوڈ کریں",
        "insurance.photo_btn": "تصویر",
        "insurance.upload_btn": "اپ لوڈ",

        "incident.title": "صورتحال بیان کریں",
        "incident.subtitle": "ہمیں بتائیں کیا ہوا۔",
        "incident.emergency_alert": "یہ جان لیوا ایمرجنسی ہو سکتی ہے",
        "incident.emergency_action": "اگر فوری ہو تو فوراً 911 کال کریں۔",
        "incident.description": "کیا ہوا؟",
        "incident.description_placeholder": "مختصراً بیان کریں...",
        "incident.care_type": "دیکھ بھال کی قسم",
        "incident.symptoms": "علامات",
        "incident.symptoms_hint": "تمام لاگو ہونے والے منتخب کریں۔",
        "incident.severity": "کتنا شدید ہے؟",

        "results.insurance": "انشورنس:",
        "results.care": "دیکھ بھال:",
        "results.location_placeholder": "مقام درج کریں",
        "results.use_gps": "GPS استعمال کریں",
        "results.locating": "تلاش...",
        "results.sort.closest": "قریب ترین",
        "results.sort.best_match": "بہترین میچ",
        "results.sort.lowest_cost": "کم ترین قیمت",
        "results.show_map": "نقشہ دکھائیں",
        "results.list_only": "صرف فہرست",
        "results.filters": "فلٹر",
        "results.filter.capability": "قلیت",
        "results.filter.insurance": "انشورنس کی حیثیت",
        "results.filter.distance": "زیادہ سے زیادہ فاصلہ",
        "results.filter.clear": "فلٹر صاف کریں",
        "results.finding": "ہسپتال تلاش کر رہے ہیں...",
        "results.no_results": "کوئی ہسپتال نہیں ملا",
        "results.no_results_hint": "فاصلہ بڑھانے کی کوشش کریں۔",

        "hospital.view_details": "تفصیلات دیکھیں",
        "hospital.call": "ہسپتال کال کریں",
        "hospital.est_cost": "تخمینی لاگت",
        "hospital.distance": "فاصلہ",
        "hospital.insurance": "انشورنس",
        "hospital.verified": "تصدیق شدہ",
        "hospital.out_of_network": "نیٹ ورک سے باہر",
        "hospital.unknown_coverage": "نامعلوم کوریج",

        "care_type.emergency": "ایمرجنسی روم (ER)",
        "care_type.urgent": "فوری دیکھ بھال",
        "care_type.not-sure": "یقین نہیں",
        "care_desc.emergency": "جان لیوا یا شدید حالت",
        "care_desc.urgent": "جان لیوا نہیں لیکن آج علاج کی ضرورت ہے",
        "care_desc.not-sure": "ہم علامات کی بنیاد پر مدد کریں گے",

        "symptom.chest-pain": "سینے میں درد",
        "symptom.stroke": "فالج کی علامات",
        "symptom.major-bleeding": "بہت زیادہ خون بہنا",
        "symptom.broken-bone": "ٹوٹی ہوئی ہڈی",
        "symptom.severe-burn": "شدید جلنا",
        "symptom.allergic-reaction": "الرجک ردعمل",
        "symptom.high-fever": "تیز بخار",
        "symptom.head-injury": "سر کی چوٹ",
        "symptom.other": "دیگر / یقین نہیں",

        "severity.mild": "معمولی",
        "severity.moderate": "درمیانی",
        "severity.severe": "شدید",
        "severity_desc.mild": "قابل انتظام",
        "severity_desc.moderate": "نمایاں لیکن مستحکم",
        "severity_desc.severe": "شدید، تیزی سے خراب",
    },
};

// Helper to fill in missing keys with English defaults
Object.keys(DICTIONARY).forEach((key) => {
    if (key === "en") return;
    const lang = key as LanguageCode;
    const missing = Object.keys(DICTIONARY.en).filter((k) => !DICTIONARY[lang][k]);
    missing.forEach((k) => {
        DICTIONARY[lang][k] = DICTIONARY.en[k];
    });
});
