import type { Hospital } from "./types";

export const MOCK_HOSPITALS: Hospital[] = [
  {
    id: "1",
    name: "NewYork-Presbyterian / Weill Cornell Medical Center",
    address: "525 E 68th St, New York, NY 10065",
    lat: 40.7649,
    lng: -73.9546,
    distanceMiles: 0.8,
    etaMinutes: 5,
    capabilities: ["ER", "Trauma I", "Stroke Center", "Burn Center", "Pediatric"],
    insuranceConfidence: "verified",
    costEstimateMin: 350,
    costEstimateMax: 1200,
    costConfidence: "high",
    phone: "(212) 746-5454",
    website: "https://www.nyp.org",
  },
  {
    id: "2",
    name: "Mount Sinai Hospital",
    address: "1 Gustave L. Levy Pl, New York, NY 10029",
    lat: 40.7903,
    lng: -73.9527,
    distanceMiles: 1.2,
    etaMinutes: 8,
    capabilities: ["ER", "Trauma I", "Stroke Center", "Pediatric"],
    insuranceConfidence: "verified",
    costEstimateMin: 400,
    costEstimateMax: 1500,
    costConfidence: "high",
    phone: "(212) 241-6500",
    website: "https://www.mountsinai.org",
  },
  {
    id: "3",
    name: "NYU Langone Health - Tisch Hospital",
    address: "550 First Ave, New York, NY 10016",
    lat: 40.7421,
    lng: -73.974,
    distanceMiles: 1.5,
    etaMinutes: 10,
    capabilities: ["ER", "Trauma I", "Stroke Center", "Pediatric"],
    insuranceConfidence: "likely",
    costEstimateMin: 500,
    costEstimateMax: 1800,
    costConfidence: "medium",
    phone: "(212) 263-7300",
    website: "https://nyulangone.org",
  },
  {
    id: "4",
    name: "Bellevue Hospital Center",
    address: "462 First Ave, New York, NY 10016",
    lat: 40.7392,
    lng: -73.977,
    distanceMiles: 1.7,
    etaMinutes: 12,
    capabilities: ["ER", "Trauma I", "Stroke Center", "Burn Center", "Pediatric"],
    insuranceConfidence: "verified",
    costEstimateMin: 150,
    costEstimateMax: 600,
    costConfidence: "high",
    phone: "(212) 562-4141",
    website: "https://www.nychealthandhospitals.org/bellevue",
  },
  {
    id: "5",
    name: "Lenox Hill Hospital",
    address: "100 E 77th St, New York, NY 10075",
    lat: 40.7743,
    lng: -73.9595,
    distanceMiles: 2.0,
    etaMinutes: 14,
    capabilities: ["ER", "Stroke Center"],
    insuranceConfidence: "likely",
    costEstimateMin: 400,
    costEstimateMax: 1400,
    costConfidence: "medium",
    phone: "(212) 434-2000",
    website: "https://www.northwell.edu/lenox-hill-hospital",
  },
  {
    id: "6",
    name: "NewYork-Presbyterian / Columbia University Irving Medical Center",
    address: "622 W 168th St, New York, NY 10032",
    lat: 40.8405,
    lng: -73.9419,
    distanceMiles: 3.1,
    etaMinutes: 20,
    capabilities: ["ER", "Trauma I", "Stroke Center", "Burn Center", "Pediatric"],
    insuranceConfidence: "verified",
    costEstimateMin: 350,
    costEstimateMax: 1300,
    costConfidence: "high",
    phone: "(212) 305-2500",
    website: "https://www.nyp.org",
  },
  {
    id: "7",
    name: "Harlem Hospital Center",
    address: "506 Lenox Ave, New York, NY 10037",
    lat: 40.8146,
    lng: -73.9387,
    distanceMiles: 3.5,
    etaMinutes: 22,
    capabilities: ["ER", "Trauma II", "Stroke Center"],
    insuranceConfidence: "unknown",
    costEstimateMin: null,
    costEstimateMax: null,
    costConfidence: "low",
    phone: "(212) 939-1000",
    website: "https://www.nychealthandhospitals.org/harlem",
  },
  {
    id: "8",
    name: "Metropolitan Hospital Center",
    address: "1901 First Ave, New York, NY 10029",
    lat: 40.7858,
    lng: -73.9439,
    distanceMiles: 2.5,
    etaMinutes: 16,
    capabilities: ["ER", "Trauma II"],
    insuranceConfidence: "likely",
    costEstimateMin: 200,
    costEstimateMax: 800,
    costConfidence: "low",
    phone: "(212) 423-6262",
    website: "https://www.nychealthandhospitals.org/metropolitan",
  },
];
